Add PR template
otus-devops-2019-05/ASMalyshev1_infra pull request #1
Opened 2019-06-19 08:24 UTC by ASMalyshev1

2019-06-19 10:56 UTC, mrgreyves requested changes
Здравствуйте!) Вам нужно добавить описание к вашему пр, так же нет интеграции с tavis и файла для проверок. Все этапы выполнения описаны в методичке к этому задания. Возвращаю на доработку.

2019-06-19 11:50 UTC, ASMalyshev1 commented
Я запутался с этими заданиями, в slack мне приходит нотификация но не могу сделать Pull Request







>Среда, 19 июня 2019, 13:56 +03:00 от Vladimir Drozdetskiy <notifications@github.com>:
>
>@mrgreyves requested changes on this pull request.
>Здравствуйте!) Вам нужно добавить описание к вашему пр, так же нет интеграции с tavis и файла для проверок. Все этапы выполнения описаны в методичке к этому задания. Возвращаю на доработку.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

С уважением,
Алексей Малышев
mail@asmalyshev.ru

2019-06-19 11:51 UTC, mrgreyves commented
Вы как раз и сделали сейчас пуллреквест =)
Помимо него вам нужно добавить в репозиторий нужные файлы =)

2019-06-19 12:01 UTC, ASMalyshev1 commented
Да похоже разобрался, в мастер ветку все пытался залить сейчас перенес в play-travis


>Среда, 19 июня 2019, 14:51 +03:00 от Vladimir Drozdetskiy <notifications@github.com>:
>
>Вы как раз и сделали сейчас пуллреквест =)
>Помимо него вам нужно добавить в репозиторий нужные файлы =)
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

С уважением,
Алексей Малышев
mail@asmalyshev.ru

2019-06-19 18:55 UTC, mrgreyves requested changes
У вас ошибки в настройке интеграции тревиса и гитхаба. Проблема в файле. Так же нет описания пр =(

2019-06-19 19:32 UTC, ASMalyshev1 commented
Как мне проверить деплой без push request? Описание куда писать в readme или в описание коммитов? 




Скачайте Outlook для Android







On Wed, Jun 19, 2019 at 9:55 PM +0300, "Vladimir Drozdetskiy" <notifications@github.com> wrote:












@mrgreyves requested changes on this pull request.





У вас ошибки в настройке интеграции тревиса и гитхаба. Проблема в файле. Так же нет описания пр =(





—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-06-19 20:06 UTC, closed without merging

2019-06-20 06:28 UTC, mrgreyves commented
Здравствуйте!) Ридми это подробная документация, описание в пр должно быть сжатым. Проверить тесты вы можете при пуше по идеи.

2019-06-20 06:31 UTC, ASMalyshev1 commented
Спасибо, сейчас у меня все нормально? 




Скачайте Outlook для Android







On Thu, Jun 20, 2019 at 9:28 AM +0300, "Vladimir Drozdetskiy" <notifications@github.com> wrote:












Здравствуйте!) Ридми это подробная документация, описание в пр должно быть сжатым. Проверить тесты вы можете при пуше по идеи.





—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-06-20 07:36 UTC, mrgreyves commented
В принципе да. Переоткройте пр и не забудьте про его описание. =)

2019-06-20 08:05 UTC, ASMalyshev1 commented
Он в очереди висит #2



>Четверг, 20 июня 2019, 10:36 +03:00 от Vladimir Drozdetskiy <notifications@github.com>:
>
>В принципе да. Переоткройте пр и не забудьте про его описание. =)
>—
>You are receiving this because you modified the open/close state.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

С уважением,
Алексей Малышев
mail@asmalyshev.ru